name: Build Electron App

on:
  release:
    types: [published]  # Automatically triggers on published releases
  workflow_dispatch:  # Allows manual trigger from the GitHub UI
jobs:
  electron-build-windows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Adjust based on your Electron requirements

      - name: Install dependencies
        run: |
          npm install
          npm install --save-dev electron electron-builder

      - name: Build Electron app
        run: |
          npm run app:dist  # Assumes you have a build script in package.json
          npx electron-builder --publish never
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts to release
        uses: actions/upload-artifact@v4
        with:
          name: windows-unpacked
          path: dist/win-unpacked  # Adjust based on your target platform(s)

      - name: Upload installer to release
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: dist/gamesentenceminer Setup*.exe  # Adjust based on your target platform(s)

      - name: Attach artifacts to release
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'release' && github.event.action == 'published'
        with:
          files: |
            dist/gamesentenceminer Setup*.exe
            dist/win-unpacked/*.exe  # Adjust to match specific files in win-unpacked
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
