name: Build Executables

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x  # Adjust Python version as needed

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Windows Executable
        run: |
          pyinstaller --noconfirm --name "MyApp" --add-data "pickaxe_icon.ico;." main.py
        env:
          PYTHONUNBUFFERED: 1

      - name: Upload Artifact (Windows)
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: dist/GameSentenceMiner

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Linux Executable
        run: |
          pyinstaller --noconfirm --name "MyApp" --add-data "pickaxe_icon.ico:." main.py
        env:
          PYTHONUNBUFFERED: 1

      - name: Upload Artifact (Linux)
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: dist/GameSentenceMiner
