name: Publish GSM

on:
  release:
    types: [published]  # Automatically triggers on published releases
  workflow_dispatch:  # Allows manual trigger from the GitHub UI

jobs:
  build-and-publish-python:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Adjust if necessary

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel twine build

      - name: Build the package
        run: |
          # python setup.py sdist bdist_wheel  # For setup.py projects
          # Uncomment the line below for pyproject.toml projects (PEP 517/518)
          python -m build

      - name: Check if version exists on PyPI
        run: |
          echo "version_exists=true" >> $GITHUB_ENV
          PACKAGE_NAME=$(python -c "import toml; print(toml.load('pyproject.toml')['project']['name'])")
          PACKAGE_VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['project']['version'])")
          if curl -s https://pypi.org/pypi/$PACKAGE_NAME/$PACKAGE_VERSION/json | grep -q "Not Found"; then
            echo "version_exists=false" >> $GITHUB_ENV

      - name: Publish package to PyPI
        if: env.version_exists == 'false'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/*
